Repository KnossosNET/Knossos.NET, pull requests merged in 2023-11, with the labels that each got.

#45 Fix custom exec names on macOS
  Knossos.NET/Classes/FsoBuild.cs
  Knossos.NET/ViewModels/Templates/DevBuildPkgMgrViewModel.cs
  Knossos.NET/ViewModels/Windows/AddUserBuildViewModel.cs
  Knossos.NET/Views/Windows/AddUserBuildView.axaml
Labels: fix

#47 fix decompression on case sensitive filesystems
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
Labels: fix

#48 Fix `Reset` not resetting `IgnoreGlobalCmd`
  Knossos.NET/ViewModels/Windows/ModSettingsViewModel.cs
Labels: fix

#46 Add .vscode/ to gitignore
  .gitignore
Labels: documentation

#51 More UI adjustments And Rename Tabs
  Knossos.NET/Assets/general/questionmark.png
  Knossos.NET/Views/FsoBuildsView.axaml
  Knossos.NET/Views/ModListView.axaml
  Knossos.NET/Views/NebulaModListView.axaml
  Knossos.NET/Views/Templates/FsoBuildItemView.axaml
  Knossos.NET/Views/Windows/MainWindow.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: enhancement

#44 Some Formatting Adjustments To Download List
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/Views/Templates/TaskItemView.axaml
Labels: enhancement

#52 Update README.md
  README.md
Labels: documentation

#57 Multiplayer screen UI adjustments
  Knossos.NET/ViewModels/PxoViewModel.cs
  Knossos.NET/Views/PxoView.axaml
Labels: cleanup

#58 Update Setup Guide
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/Windows/QuickSetupViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: documentation, fix, cleanup

#56 Main Dev Tab and Packages sub-tab Margin Adjustments and text wrapping
  Knossos.NET/Views/DeveloperModsView.axaml
  Knossos.NET/Views/Templates/DevModEditorView.axaml
  Knossos.NET/Views/Templates/DevModPkgMgrView.axaml
Labels: cleanup

#62 Settings Tab Overhaul
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/PerformanceHelpView.axaml
Labels: cleanup

#64 Update Quick Setup Guide button text
  Knossos.NET/Views/Windows/PerformanceHelpView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: documentation, cleanup

#63 Move update/modify to main tab in modcard
  Knossos.NET/Views/Templates/ModCardView.axaml
Labels: cleanup

#66 Add DevEnv mod version support
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModVersionsViewModel.cs
  Knossos.NET/Views/Templates/DevModVersionsView.axaml
Labels: enhancement

#70 Two Fixes
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/ModSettingsView.axaml
Labels: fix, cleanup

#72 Put This button in its own wrap panel
  Knossos.NET/Views/Templates/DevModVersionsView.axaml
Labels: cleanup

#68 Mod compression changes/fixes
  IonKiwi.lz4/LZ4RawUtility.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  VP.NET/VPCompression.cs
  VP.NET/VPContainer.cs
  VP.NET/VPFile.cs
Labels: fix

#75 Remove span html, remove list hack
  Knossos.NET/Classes/BBCode.cs
  Knossos.NET/ViewModels/Windows/DevModDescriptionEditorViewModel.cs
  Knossos.NET/ViewModels/Windows/ModDetailsViewModel.cs
  Knossos.NET/Views/Windows/DevModDescriptionEditorView.axaml
Labels: fix

#74 Adjust UI Button Colors
  Knossos.NET/AppStyles.axaml
  Knossos.NET/ViewModels/Templates/DevModVersionsViewModel.cs
  Knossos.NET/Views/DeveloperModsView.axaml
  Knossos.NET/Views/FsoBuildsView.axaml
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/PxoView.axaml
  Knossos.NET/Views/Templates/DevBuildPkgMgrView.axaml
  Knossos.NET/Views/Templates/DevModDetailsView.axaml
  Knossos.NET/Views/Templates/DevModEditorView.axaml
  Knossos.NET/Views/Templates/DevModFsoSettingsView.axaml
  Knossos.NET/Views/Templates/DevModPkgMgrView.axaml
  Knossos.NET/Views/Templates/DevModVersionsView.axaml
  Knossos.NET/Views/Templates/FsoBuildItemView.axaml
  Knossos.NET/Views/Templates/FsoBuildPickerView.axaml
  Knossos.NET/Views/Templates/ModCardView.axaml
  Knossos.NET/Views/Templates/NebulaLoginView.axaml
  Knossos.NET/Views/Windows/Fs2InstallerView.axaml
  Knossos.NET/Views/Windows/MainWindow.axaml
  Knossos.NET/Views/Windows/ModDetailsView.axaml
Labels: cleanup
