Repository KnossosNET/Knossos.NET, pull requests merged in 2023-12, with the labels that each got.

#77 Do not delete pxo login data during globalsettings reset
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
Labels: fix

#79 Fix path writing in browse to build on mac
  Knossos.NET/Classes/FsoBuild.cs
Labels: fix

#76 Fix three small button issues
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/ModDetailsView.axaml
Labels: fix

#84 Newerest -> Newest
  Knossos.NET/Views/Windows/ModDetailsView.axaml
Labels: cleanup

#82 Refresh the ini if preferred path changes
  Knossos.NET/Classes/KnUtils.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
Labels: fix

#83 Set progress when decompress is complete
  Knossos.NET/Classes/KnUtils.cs
Labels: fix

#90 fix previous quick setup repo load fix
  Knossos.NET/Models/Nebula.cs
Labels: fix

#91 Make task name bigger and progressbar smaller, and replace "_" for "-"
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/Views/Templates/TaskItemView.axaml
Labels: cleanup

#93 Fix dependency processing during mod install
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
Labels: fix, cleanup

#86 Community tab
  Knossos.NET/AppStyles.axaml
  Knossos.NET/Assets/general/discordicon.png
  Knossos.NET/Assets/general/fred.png
  Knossos.NET/Assets/general/fsolua.png
  Knossos.NET/Assets/general/github.png
  Knossos.NET/Classes/FaqQuestion.cs
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/ViewModels/CommunityViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/CommunityView.axaml
  Knossos.NET/Views/CommunityView.axaml.cs
  Knossos.NET/Views/Windows/MainWindow.axaml
Labels: enhancement

#92 Some more button polishing and change build install background to solid
  Knossos.NET/AppStyles.axaml
  Knossos.NET/Views/FsoBuildsView.axaml
  Knossos.NET/Views/Templates/NebulaLoginView.axaml
  Knossos.NET/Views/Windows/ModDetailsView.axaml
  Knossos.NET/Views/Windows/ModInstallView.axaml
Labels: cleanup

#100 Update Avalonia to 11.0.6 and HTTP extension to 8.0.0
  Knossos.NET/Knossos.NET.csproj
Labels: enhancement

#98 Update FRED Tutorial Link
  Knossos.NET/ViewModels/CommunityViewModel.cs
  Knossos.NET/Views/CommunityView.axaml
Labels: cleanup

#101 Filter system flags out of mod cmdline
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/GlobalSettings.cs
Labels: bug, enhancement

#99 Support mod metadata update
  Knossos.NET/Models/Mod.cs
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
  Knossos.NET/Views/Windows/ModInstallView.axaml
Labels: enhancement

#95 Make the search bar retain search terms between tabs
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
Labels: enhancement

#88 Allow to modify FSO builds and only install the best build for user system
  Knossos.NET/Classes/FsoBuild.cs
  Knossos.NET/Models/Mod.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/FsoBuildItemViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/Views/Templates/FsoBuildItemView.axaml
Labels: cleanup

#97 Add cleanup old mod versions option to mod install
  Knossos.NET/ViewModels/DeveloperModsViewModel.cs
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/ModCardViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
  Knossos.NET/Views/Windows/ModInstallView.axaml
Labels: enhancement

#102 Allow sorting behavior to persist
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
Labels: enhancement

#106 Fix mod settings not being saved
  Knossos.NET/ViewModels/Templates/DevModFsoSettingsViewModel.cs
Labels: fix

#113 Fix small typo
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: cleanup

#111 Filter Mod Details screen buttons by Mod type And Make Version text instead of a combobox for build details
  Knossos.NET/ViewModels/Windows/ModDetailsViewModel.cs
  Knossos.NET/Views/Windows/ModDetailsView.axaml
Labels: cleanup

#110 Give Build Name More Room
  Knossos.NET/Views/Templates/FsoBuildItemView.axaml
Labels: cleanup

#114 Fix update system once again
  Knossos.NET/Assets/scripts/update_linux.sh
  Knossos.NET/Assets/scripts/update_mac.sh
  Knossos.NET/Assets/scripts/update_windows.cmd
  Knossos.NET/Classes/KnUtils.cs
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Knossos.NET.csproj
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
Labels: fix

#94 add installer for Windows
  .github/workflows/build_release.yml
  ci/create_win_installer.sh
  packaging/windows/knossos.nsi
Labels: enhancement

#108 Download Convenience Buttons
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/DeveloperModsViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/ViewModels/Windows/QuickSetupViewModel.cs
  Knossos.NET/Views/DeveloperModsView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: enhancement

#118 make sure copied files are lower case during retail install
  Knossos.NET/ViewModels/Windows/Fs2InstallerViewModel.cs
Labels: fix

#119 Fix all instances of seetings
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/Models/ModSettings.cs
  Knossos.NET/Models/Nebula.cs
Labels: cleanup

#121 allow quick launch to close down properly
  Knossos.NET/Classes/Knossos.cs
Labels: fix
