Repository KnossosNET/Knossos.NET, pull requests merged in 2024-03, with the labels that each got.

#162 finish updating public facing `Command Line` text
  Knossos.NET/Views/Templates/FsoFlagsView.axaml
  README.md
Labels: documentation, cleanup

#161 Fix Knossos Not sorting mods on startup
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
Labels: fix

#157 Add Version Date to Install Screen
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
  Knossos.NET/Views/Windows/ModInstallView.axaml
Labels: enhancement

#159 Select by default newly added, recommended, mod pkgs during mod install
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
Labels: enhancement

#167 Set File.Move() on installer update.exe update to override existing file
  Knossos.NET/Classes/Knossos.cs
Labels: fix

#160 Improve New Mod Name During Creation
  Knossos.NET/ViewModels/Windows/DevModCreateNewViewModel.cs
Labels: fix

#168 Ignore installed builds whiout any valid executables when clicking play
  Knossos.NET/Classes/FsoBuild.cs
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/Mod.cs
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
Labels: fix

#174 create user app data directory if it doesn't exist
  Knossos.NET/Classes/KnUtils.cs
Labels: fix

#173 Fix installing compressed fso versions
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: fix

#175 update icons used for Linux packages
  ci/bundle_appimage.sh
  packaging/linux/knossos-128.png
  packaging/linux/knossos-16.png
  packaging/linux/knossos-256.png
  packaging/linux/knossos-32.png
  packaging/linux/knossos-48.png
  packaging/linux/knossos-512.png
  packaging/linux/knossos-64.png
  packaging/linux/knossos-96.png
Labels: enhancement

#176 fix hang on Mac preventing repo load
  Knossos.NET/Classes/Knossos.cs
Labels: fix

#179 clean up a few UI/UX things
  Knossos.NET/App.axaml
  Knossos.NET/Classes/KnUtils.cs
  Knossos.NET/Converters/EscapeUnderscoresConverter.cs
  Knossos.NET/ViewModels/Templates/FsoBuildItemViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Windows/ModSettingsViewModel.cs
  Knossos.NET/Views/DeveloperModsView.axaml
  Knossos.NET/Views/ModListView.axaml
  Knossos.NET/Views/NebulaModListView.axaml
  Knossos.NET/Views/Templates/DevBuildPkgMgrView.axaml
  Knossos.NET/Views/Templates/DevModDetailsView.axaml
  Knossos.NET/Views/Templates/DevModPkgMgrView.axaml
  Knossos.NET/Views/Templates/FsoBuildItemView.axaml
  Knossos.NET/Views/Templates/TaskItemView.axaml
  Knossos.NET/Views/Windows/MainWindow.axaml
  Knossos.NET/Views/Windows/ModDetailsView.axaml
  Knossos.NET/Views/Windows/ReportModView.axaml
Labels: fix, cleanup, ui

#177 Update Settings headings with some slight tuning
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: cleanup
