Repository KnossosNET/Knossos.NET, pull requests merged in 2024-01, with the labels that each got.

#126 make sure tool executables are signed on Mac
  Knossos.NET/Classes/Tool.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
Labels: fix

#129 Add image file size limits to mod editor
  Knossos.NET/ViewModels/Templates/DevModDetailsViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModVersionsViewModel.cs
  Knossos.NET/Views/Templates/DevModDetailsView.axaml
Labels: cleanup

#132 fix some spelling errors
  Knossos.NET/Classes/KnUtils.cs
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModVersionsViewModel.cs
  Knossos.NET/ViewModels/Templates/ModCardViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Windows/Fs2InstallerViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/ViewModels/Windows/ModDetailsViewModel.cs
  Knossos.NET/ViewModels/Windows/ModSettingsViewModel.cs
  Knossos.NET/Views/ModListView.axaml
  Knossos.NET/Views/Templates/DevModDetailsView.axaml
  Knossos.NET/Views/Templates/ModCardView.axaml
  Knossos.NET/Views/Windows/Fs2InstallerView.axaml
  Knossos.NET/Views/Windows/ModDetailsView.axaml
  Knossos.NET/Views/Windows/ModSettingsView.axaml
Labels: cleanup

#131 remove list padding to fix layout issue on mod descriptions
  Knossos.NET/Classes/BBCode.cs
Labels: fix

#134 fix and tweak mod details view
  Knossos.NET/ViewModels/Windows/ModDetailsViewModel.cs
  Knossos.NET/Views/Windows/ModDetailsView.axaml
Labels: fix, cleanup

#133 Improve default visibility of bottom buttons on quicksetup guide
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: cleanup

#128 Load NebulaModCard images only when the card is visible
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
  Knossos.NET/ViewModels/Templates/NebulaModCardViewModel.cs
Labels: cleanup

#136 fix regex to prevent dashes in mod ids
  Knossos.NET/ViewModels/Windows/DevModCreateNewViewModel.cs
Labels: fix

#138 Update color on QuickSetup Guide
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: enhancement

#141 Fix aa preset flag setting bug
  Knossos.NET/Models/GlobalSettings.cs
Labels: fix

#145 Fix explore tab search during initial load
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
Labels: bug

#144 Make root_fs2.vp detection case insensitive
  Knossos.NET/Classes/Knossos.cs
Labels: bug

#146 Add scrollbar to msgbox
  Knossos.NET/Views/Windows/MessageBox.axaml
Labels: enhancement

#142 BTA Changes, aka TC mods changes
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/ViewModels/Templates/DevModPkgMgrViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModVersionsViewModel.cs
Labels: enhancement

#143 Mod install/modify rework
  Knossos.NET/Models/Mod.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
  Knossos.NET/Views/Windows/ModInstallView.axaml
Labels: enhancement
