Repository KnossosNET/Knossos.NET, pull requests merged in 2024-12, with the labels that each got.

#248 Split tasks code into individual files
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Templates/Tasks/CompressLosseFiles.cs
  Knossos.NET/ViewModels/Templates/Tasks/CompressMod.cs
  Knossos.NET/ViewModels/Templates/Tasks/CompressVP.cs
  Knossos.NET/ViewModels/Templates/Tasks/CreateModNebula.cs
  Knossos.NET/ViewModels/Templates/Tasks/CreateModVersion.cs
  Knossos.NET/ViewModels/Templates/Tasks/DecompressLosseFiles.cs
  Knossos.NET/ViewModels/Templates/Tasks/DecompressMod.cs
  Knossos.NET/ViewModels/Templates/Tasks/DecompressNebulaFile.cs
  Knossos.NET/ViewModels/Templates/Tasks/DecompressVP.cs
  Knossos.NET/ViewModels/Templates/Tasks/DisplayUpdates.cs
  Knossos.NET/ViewModels/Templates/Tasks/DownloadFile.cs
  Knossos.NET/ViewModels/Templates/Tasks/ExtractVP.cs
  Knossos.NET/ViewModels/Templates/Tasks/InstallBuild.cs
  Knossos.NET/ViewModels/Templates/Tasks/InstallMod.cs
  Knossos.NET/ViewModels/Templates/Tasks/InstallTool.cs
  Knossos.NET/ViewModels/Templates/Tasks/PreFlightCheck.cs
  Knossos.NET/ViewModels/Templates/Tasks/PrepareModPkg.cs
  Knossos.NET/ViewModels/Templates/Tasks/ReleaseMod.cs
  Knossos.NET/ViewModels/Templates/Tasks/ShowMsg.cs
  Knossos.NET/ViewModels/Templates/Tasks/TryToCopyFilesFromOldVersions.cs
  Knossos.NET/ViewModels/Templates/Tasks/UploadModImages.cs
  Knossos.NET/ViewModels/Templates/Tasks/UploadModPkg.cs
  Knossos.NET/ViewModels/Templates/Tasks/UploadModVersion.cs
  Knossos.NET/ViewModels/Templates/Tasks/VerifyMod.cs
Labels: cleanup

#254 Do not start the UI when using the "-playmod" cmdline argument
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Program.cs
Labels: cleanup

#256 Change modcards to 3 tabs
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/ViewModels/Templates/ModCardViewModel.cs
  Knossos.NET/Views/Templates/ModCardView.axaml
Labels: enhancement

#258 In devmode do not load dependencies of disabled packages
  Knossos.NET/Models/Mod.cs
Labels: bug

#262 Fix 7z verify failling if the knossos library has spaces in the path
  Knossos.NET/Classes/SevenZipConsoleWrapper.cs
Labels: bug

#263 Fix some spelling
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
Labels: cleanup
