Repository KnossosNET/Knossos.NET, pull requests merged in 2024-10, with the labels that each got.

#226 Disable max crc check attempts and remove cancel on 7z compression fail
  Knossos.NET/Classes/KnUtils.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
Labels: cleanup

#240 Refresh dev fso build list during builds install/delete and add reload depedency button
  Knossos.NET/ViewModels/DeveloperModsViewModel.cs
  Knossos.NET/ViewModels/FsoBuildsViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModEditorViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModFsoSettingsViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModPkgMgrViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/Views/Templates/DevModPkgMgrView.axaml
Labels: bug, enhancement

#245 Add warning for the new FSO 24.2 settings system
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/MessageBox.axaml.cs
Labels: cleanup

#242 Advanced mod upload
  Knossos.NET/App.axaml
  Knossos.NET/Knossos.NET.csproj
  Knossos.NET/Models/Mod.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModVersionsViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Windows/DevModAdvancedUploadViewModel.cs
  Knossos.NET/Views/Templates/DevModVersionsView.axaml
  Knossos.NET/Views/Windows/DevModAdvancedUploadView.axaml
  Knossos.NET/Views/Windows/DevModAdvancedUploadView.axaml.cs
Labels: enhancement

#246 Update helper wording based on user-feedback
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: documentation, cleanup
