Repository KnossosNET/Knossos.NET, pull requests merged in 2024-05, with the labels that each got.

#194 Fix typo error causing a crash opening mod details with null screenshots
  Knossos.NET/ViewModels/Windows/ModDetailsViewModel.cs
Labels: bug

#187 Change "multiupload/finish" timeout to 160 seconds
  Knossos.NET/Models/Nebula.cs
Labels: cleanup

#184 Support running Fred2 on Linux using Wine
  Knossos.NET/Classes/FsoBuild.cs
  Knossos.NET/Classes/Wine.cs
  Knossos.NET/ViewModels/Templates/FsoBuildItemViewModel.cs
Labels: enhancement

#189 Make joystick combobox bigger
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: enhancement

#191 Add "Clean Nightlies" button
  Knossos.NET/ViewModels/FsoBuildsViewModel.cs
  Knossos.NET/Views/FsoBuildsView.axaml
Labels: enhancement

#190 Catch the exception when this task get cancelled on closing Knet
  Knossos.NET/ViewModels/TaskViewModel.cs
Labels: bug

#192 Implement temporal cache for nebula "mod/json" GET calls
  Knossos.NET/Models/Nebula.cs
Labels: enhancement

#193 Add sorting function to devmode tab mod list
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/ViewModels/DeveloperModsViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/DeveloperModsView.axaml
Labels: enhancement

#196 Move Screenshots button to main window
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/ModListView.axaml
  Knossos.NET/Views/Windows/MainWindow.axaml
Labels: enhancement

#197 Add toggle task view function
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskInfoButtonViewModel.cs
  Knossos.NET/Views/Templates/TaskInfoButtonView.axaml
Labels: enhancement
