Repository KnossosNET/Knossos.NET, pull requests merged in 2024-08, with the labels that each got.

#217 Warn about bad library folder
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
Labels: fix

#216 Adapt loading animations for mod tile tabs
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
  Knossos.NET/ViewModels/Templates/LoadingIconViewModel.cs
  Knossos.NET/Views/ModListView.axaml
  Knossos.NET/Views/NebulaModListView.axaml
  Knossos.NET/Views/Templates/LoadingIconView.axaml
  Knossos.NET/Views/Templates/LoadingIconView.axaml.cs
Labels: enhancement

#220 Use Local instead of Absolute path
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
Labels: fix

#221 Add CRC check during mod upload
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
Labels: enhancement, fix

#222 Add update available banner to mod cards
  Knossos.NET/Assets/general/upd_icon.png
  Knossos.NET/Views/Templates/ModCardView.axaml
Labels: enhancement
