Repository KnossosNET/Knossos.NET, pull requests merged in 2024-06, with the labels that each got.

#202 Select Tools by index rather than checking the IsSelected value
  Knossos.NET/ViewModels/Templates/DevModEditorViewModel.cs
Labels: bug

#200 Check API result value on upload log and report mod Api Calls
  Knossos.NET/Models/Nebula.cs
Labels: bug

#199 Add Talos to the list of allowed/disallowed mirrors
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: enhancement

#198 Support loading mod id that are in the modflag but not in the dp list
  Knossos.NET/Classes/Knossos.cs
Labels: enhancement

#203 Implement FSO builds autoupdate function
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/FsoBuildItemViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: enhancement

#208 Search other mod versions for files instead of download
  Knossos.NET/Classes/HardLink.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/TaskItemViewModel.cs
  Knossos.NET/ViewModels/Windows/ModInstallViewModel.cs
  Knossos.NET/Views/Windows/ModInstallView.axaml
Labels: cleanup

#209 Fix engine and community tabs layout
  Knossos.NET/ViewModels/Templates/FsoBuildItemViewModel.cs
  Knossos.NET/Views/CommunityView.axaml
  Knossos.NET/Views/Templates/FsoBuildItemView.axaml
Labels: fix, ui
