Repository KnossosNET/Knossos.NET, pull requests merged in 2025-01, with the labels that each got.

#250 Implement portable mode
  Knossos.NET/Classes/FsoBuild.cs
  Knossos.NET/Classes/KnUtils.cs
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/Models/Log.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/ViewModels/Windows/QuickSetupViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: enhancement

#264 Remove aigaion from the mirror list
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: cleanup

#266 Fix mod settings were not saving on newely installed mods until restart
  Knossos.NET/Models/ModSettings.cs
  Knossos.NET/ViewModels/Templates/Tasks/InstallMod.cs
Labels: bug

#267 Add Sectioning to Options Menu
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/Tasks/CreateModVersion.cs
  Knossos.NET/ViewModels/Templates/Tasks/InstallTool.cs
  Knossos.NET/ViewModels/Windows/DevModCreateNewViewModel.cs
  Knossos.NET/ViewModels/Windows/Fs2InstallerViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Templates/DevModPkgMgrView.axaml
  Knossos.NET/Views/Windows/AddSapiVoicesView.axaml
  Knossos.NET/Views/Windows/CleanupKnossosLibraryView.axaml
  Knossos.NET/Views/Windows/DevModAdvancedUploadView.axaml
  Knossos.NET/Views/Windows/DevModCreateNewView.axaml
  Knossos.NET/Views/Windows/Fs2InstallerView.axaml
  Knossos.NET/Views/Windows/ModInstallView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
  README.md
Labels: enhancement, cleanup

#269 Change default renderer to software
  Knossos.NET/Program.cs
Labels: cleanup

#268 Advanced mod upload not selecting last version when unselecting upload
  Knossos.NET/ViewModels/Windows/DevModAdvancedUploadViewModel.cs
  Knossos.NET/Views/Windows/DevModAdvancedUploadView.axaml
Labels: bug

#270 Update default values
  Knossos.NET/Models/GlobalSettings.cs
Labels: cleanup

#271 Tool Rework + Bonus
  Knossos.NET/AppStyles.axaml
  Knossos.NET/Classes/KnUtils.cs
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Classes/Tool.cs
  Knossos.NET/Classes/Wine.cs
  Knossos.NET/Knossos.NET.csproj
  Knossos.NET/Program.cs
  Knossos.NET/ViewModels/TaskViewModel.cs
  Knossos.NET/ViewModels/Templates/DevModEditorViewModel.cs
  Knossos.NET/ViewModels/Templates/DevToolManagerViewModel.cs
  Knossos.NET/ViewModels/Windows/ModSettingsViewModel.cs
  Knossos.NET/Views/Templates/DevToolManagerView.axaml
Labels: enhancement, cleanup

#272 Cleanup Instructions and Icons
  Knossos.NET/Assets/general/menu_debug.png
  Knossos.NET/Assets/general/menu_explore.png
  Knossos.NET/Assets/general/menu_home.png
  Knossos.NET/Assets/general/menu_play.png
  Knossos.NET/Assets/general/menu_settings.png
  Knossos.NET/ViewModels/Windows/ModSettingsViewModel.cs
  Knossos.NET/Views/DebugView.axaml
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/PerformanceHelpView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: cleanup

#273 Make Settings Tab always consistent
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/CustomHomeView.axaml
  Knossos.NET/Views/CustomHomeView.axaml.cs
Labels: documentation, question, cleanup, ui

#274 Allow TC Mode to alter Nebula text regarding 'Download' and 'Up-to-Date' messages
  Knossos.NET/Models/CustomLauncher.cs
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/Windows/DevModCreateNewViewModel.cs
  Knossos.NET/Views/CustomHomeView.axaml
Labels: enhancement

#279 Add mouse over configuration options for custom home view and add more button ids
  Knossos.NET/Models/CustomLauncher.cs
  Knossos.NET/Views/CustomHomeView.axaml
  Knossos.NET/Views/CustomHomeView.axaml.cs
Labels: cleanup

#275 Sort and filtering rework, and add basic mod tag support
  Knossos.NET/AppStyles.axaml
  Knossos.NET/Assets/general/sort-icon.png
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Classes/ModTags.cs
  Knossos.NET/Knossos.NET.csproj
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/Models/Mod.cs
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
  Knossos.NET/ViewModels/Templates/ModCardViewModel.cs
  Knossos.NET/ViewModels/Templates/NebulaModCardViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/ModListView.axaml
  Knossos.NET/Views/ModListView.axaml.cs
  Knossos.NET/Views/NebulaModListView.axaml
  Knossos.NET/Views/NebulaModListView.axaml.cs
  Knossos.NET/Views/Templates/ModCardView.axaml
  Knossos.NET/Views/Templates/NebulaModCardView.axaml
Labels: enhancement, cleanup, ui
