Repository KnossosNET/Knossos.NET, pull requests merged in 2025-02, with the labels that each got.

#281 Logging rework
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/Log.cs
  Knossos.NET/Models/Nebula.cs
  Knossos.NET/ViewModels/Templates/ModCardViewModel.cs
  Knossos.NET/ViewModels/Templates/NebulaModCardViewModel.cs
Labels: cleanup

#284 Some nebula API adjustments
  Knossos.NET/Models/Nebula.cs
Labels: cleanup

#285 Set minimal launcher dimensions and separate those values in custom mode
  Knossos.NET/Models/CustomLauncher.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/Windows/MainWindow.axaml
Labels: ui

#289 Move additional Mod classes outside mod.cs
  Knossos.NET/Models/Mod.cs
  Knossos.NET/Models/ModDependency.cs
  Knossos.NET/Models/ModExecutable.cs
  Knossos.NET/Models/ModFile.cs
  Knossos.NET/Models/ModFileList.cs
  Knossos.NET/Models/ModMember.cs
  Knossos.NET/Models/ModPackage.cs
  Knossos.NET/Models/ModProperties.cs
Labels: cleanup

#280 Feature: Skip launcher updates
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/Views/Windows/MessageBox.axaml.cs
Labels: enhancement

#282 Nebula login view rework
  Knossos.NET/ViewModels/Templates/NebulaLoginViewModel.cs
  Knossos.NET/Views/Templates/NebulaLoginView.axaml
Labels: ui

#288 Handle Nebula token is expired
  Knossos.NET/Models/Nebula.cs
Labels: fix

#287 Support APNG banners and screenshoots in Mod Details Window
  Knossos.NET/AppStyles.axaml
  Knossos.NET/ViewModels/Windows/ModDetailsViewModel.cs
  Knossos.NET/Views/Templates/DevModDetailsView.axaml
  Knossos.NET/Views/Windows/ModDetailsView.axaml
Labels: enhancement, ui

#295 Adapt globalsettings, community and developer views to work correctly with the minimal width
  Knossos.NET/Views/CommunityView.axaml
  Knossos.NET/Views/DeveloperModsView.axaml
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: cleanup, ui

#296 Add "show me where" to quick setup
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/ViewModels/Windows/QuickSetupViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
  Knossos.NET/Views/Windows/QuickSetupView.axaml
Labels: enhancement

#297 Hides the Build Settings Warning in TC Mode
  Knossos.NET/Classes/Knossos.cs
Labels: documentation, cleanup

#292 Allow TC Mode to Hide QuickStart Button
  Knossos.NET/Models/CustomLauncher.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: documentation, enhancement

#294 Update dependencies
  Knossos.NET/Knossos.NET.csproj
Labels: cleanup

#290 Add experimental tray icon
  Knossos.NET/App.axaml.cs
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/Models/Mod.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: enhancement

#300 Change trayicon to close to tray mode
  Knossos.NET/App.axaml.cs
  Knossos.NET/Models/GlobalSettings.cs
  Knossos.NET/ViewModels/GlobalSettingsViewModel.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: cleanup

#301 Improve how custom main window size is applied
  Knossos.NET/App.axaml.cs
  Knossos.NET/ViewModels/Windows/MainWindowViewModel.cs
  Knossos.NET/Views/Windows/MainWindow.axaml
  Knossos.NET/Views/Windows/MainWindow.axaml.cs
Labels: cleanup

#302 Hide more advanced video options
  Knossos.NET/Views/GlobalSettingsView.axaml
Labels: cleanup

#303 Hide 3.8.0-2 fso build from the UI
  Knossos.NET/ViewModels/FsoBuildsViewModel.cs
Labels: cleanup

#304 Move minWidth For better spacing on tabs
  Knossos.NET/Views/DeveloperModsView.axaml
Labels: ui

#298 Bump-to-1.3.0, and update readme for the new version
  Knossos.NET/Classes/Knossos.cs
  README.md
Labels: documentation

#307 Adjust modcard margin that was causing problem for 125% DPI
  Knossos.NET/Views/Templates/ModCardView.axaml
Labels: fix, ui

#309 Add filter/sort text
  Knossos.NET/ViewModels/ModListViewModel.cs
  Knossos.NET/ViewModels/NebulaModListViewModel.cs
  Knossos.NET/Views/ModListView.axaml
  Knossos.NET/Views/NebulaModListView.axaml
Labels: ui

#308 Allow to reset or ignore ingame options from mod settings window
  Knossos.NET/Classes/Knossos.cs
  Knossos.NET/Models/ModSettings.cs
  Knossos.NET/ViewModels/Windows/ModSettingsViewModel.cs
  Knossos.NET/Views/Windows/ModSettingsView.axaml
Labels: cleanup
